name: ci

on:
  push:

permissions:
  contents: read

jobs:
  appdmg:
    strategy:
      fail-fast: false
      matrix:
        macos: [ 'macos-11', 'macos-12', 'macos-13', 'macos-14' ]

    runs-on: ${{ matrix.macos}}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
